name: test
on:
  push:
    branches:
      # - master
      - morninng/feat/INV-117_githubaction_test_lint 
jobs:
  client-test:
    runs-on: ubuntu-latest
    steps:
      - name: echo
        run: echo 'aaa bbb ccc'